### ISSUE TITLE
Cooccurence module ends with an error

### ISSUE THREAD

**Issue by nkleinbo** [metagenomics/metagenomics-tk#118]
Error in console:
```
[73/c51673] NOTE: Process `wPipeline:_wAggregate:wCooccurrenceList:_wCooccurrence:pBuildNetwork (1)` terminated with an error exit status (1) -- Execution is retried (1)
[e8/886ba9] NOTE: Process `wPipeline:_wAggregate:wCooccurrenceList:_wCooccurrence:pBuildNetwork (1)` terminated with an error exit status (1) -- Execution is retried (2)
[21/c41642] NOTE: Process `wPipeline:_wAggregate:wCooccurrenceList:_wCooccurrence:pBuildNetwork (1)` terminated with an error exit status (1) -- Execution is retried (3)
[dd/4ef141] NOTE: Process `wPipeline:_wAggregate:wCooccurrenceList:_wCooccurrence:pBuildNetwork (1)` terminated with an error exit status (1) -- Error is ignored
```

Error in .command.err:
```
Unable to find image 'pbelmann/cooccurrence:0.1.6' locally
0.1.6: Pulling from pbelmann/cooccurrence
2dffa903b83a: Pulling fs layer
10f3fdbe572d: Pulling fs layer
663fe05835c5: Pulling fs layer
7a88b43f1097: Pulling fs layer
ff9b12da32ab: Pulling fs layer
bd3fedd8743f: Pulling fs layer
e936c1da0786: Pulling fs layer
929d6617a74f: Pulling fs layer
15f2d2475199: Pulling fs layer
f00f2e52599a: Pulling fs layer
b5c4c9c7ba94: Pulling fs layer
e936c1da0786: Waiting
929d6617a74f: Waiting
15f2d2475199: Waiting
ff9b12da32ab: Waiting
7a88b43f1097: Waiting
bd3fedd8743f: Waiting
b5c4c9c7ba94: Waiting
10f3fdbe572d: Verifying Checksum
10f3fdbe572d: Download complete
2dffa903b83a: Verifying Checksum
2dffa903b83a: Download complete
ff9b12da32ab: Verifying Checksum
ff9b12da32ab: Download complete
663fe05835c5: Verifying Checksum
663fe05835c5: Download complete
7a88b43f1097: Verifying Checksum
7a88b43f1097: Download complete
2dffa903b83a: Pull complete
10f3fdbe572d: Pull complete
929d6617a74f: Verifying Checksum
929d6617a74f: Download complete
663fe05835c5: Pull complete
7a88b43f1097: Pull complete
ff9b12da32ab: Pull complete
15f2d2475199: Verifying Checksum
15f2d2475199: Download complete
e936c1da0786: Verifying Checksum
e936c1da0786: Download complete
b5c4c9c7ba94: Verifying Checksum
b5c4c9c7ba94: Download complete
f00f2e52599a: Verifying Checksum
bd3fedd8743f: Verifying Checksum
bd3fedd8743f: Download complete
bd3fedd8743f: Pull complete
e936c1da0786: Pull complete
929d6617a74f: Pull complete
15f2d2475199: Pull complete
f00f2e52599a: Pull complete
b5c4c9c7ba94: Pull complete
Digest: sha256:02137fb34232700bbeb9e682b2e5eb83bd289cc177cd2f7c53946691ce1f57fb
Status: Downloaded newer image for pbelmann/cooccurrence:0.1.6
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Attaching package: ‘igraph’

The following objects are masked from ‘package:dplyr’:

    as_data_frame, groups, union

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union


Attaching package: ‘SpiecEasi’

The following object is masked from ‘package:igraph’:

    make_graph

Error in colSums(trimmed_mean_wide_inverted == 0) : 
  'x' must be an array of at least two dimensions
Calls: run_main -> colSums
Execution halted

```

Config:
```
tempdir: "tmp"
summary: false
input:
  paired:
    path: "/mnt/meta_omics/reads_split_1.tsv"
    watch: false
output: "output"
logDir: log
runid: 1
databases: "/mnt/databases/"
logLevel: 1
scratch: "/mnt/meta_omics/workdir/"
steps:
  qc:
    fastp:
       # Example params: " --cut_front --cut_tail --detect_adapter_for_pe  "
       additionalParams: "  "
  assembly:
    megahit:
      additionalParams: " --min-contig-len 1000 "
      fastg: true
  binning:
    bowtie:
      additionalParams: 
        bowtie: " --quiet --very-sensitive "
        # samtools flags are used to filter resulting bam file
        samtoolsView: " -F 3584 " 
    metabat:
      additionalParams: " --seed 234234  "
  magAttributes:
    gtdb:
      buffer: 1000
      database: "/mnt/databases/gtdb/release202"
      additionalParams: " --min_af 0.65 "
    checkm:
      database: "/mnt/databases/checkm"
      buffer: 200
      additionalParams:
        tree: " --reduced_tree "
        lineage_set: " " 
        qa: "  "
    prokka:
      defaultKingdom: 'Bacteria'
      additionalParams: " --mincontiglen 1000 "
#  fragmentRecruitment:
#    frhit:
#      genomes: "/vol/spool/meta/test/data/bin.*.fa"
#      sort: true
#      additionalParams: 
#        frhit: " -c 95 "
#        coverm: " --min-covered-fraction 0 "
  dereplication:
    pasolli:
      minimumCompleteness: 0
      maximumContamination: 5000
      ANIBuffer: 20
      mashBuffer: 2000
      method: 'ANI'
      additionalParams:
        mash_sketch: ""
        mash_dist: ""
        # cluster cutoff
        cluster: " -c 0.05 "
        pyani: " -m ANIb "
        representativeAniCutoff: 0.95
  readMapping:
    bwa:
      additionalParams:
        bwa_index: ""
        bwa_mem: ""
        coverm: " --min-covered-fraction 0 "
  cooccurrence:
    additionalParams: " -t 0.1 -z 80 -o 'correlation' "
  plasmid:
    SCAPP:
      additionalParams: "   "
    PlasClass:
      threshold: 0.5 
      additionalParams: "   "
    PLSDB:
      database: 
        source: https://openstack.cebitec.uni-bielefeld.de:8080/databases/plsdb.zip
        md5sum: caa846fbb689deba0e35ef559793b521
      sharedKmerThreshold: 30
      additionalParams:
        mashSketch: " -S 42 -k 21 -s 1000 "
        mashDist: " -v 0.2 -d 0.2 "
  annotation:
     s5cmd:
        params: '--retry-count 30 --no-verify-ssl --endpoint-url https://openstack.cebitec.uni-bielefeld.de:8080'
        #        keyfile: 'xxx'
     diamond:
        database: '/mnt/databases/kegg-2021-01.dmnd'
        params: 'blastp --fast --outfmt 6 --max-target-seqs 100 --evalue 0.1'
     kegg:
        database: '/mnt/databases/kegg_2021-01/'
     rgi: 
        source: https://openstack.cebitec.uni-bielefeld.de:8080/databases/data
        md5sum: ddc655280ef838923d8d72e42833b33c
        additionalParams: ""
     prodigal:
         mode: 'meta'
     keggFromDiamond:
resources:
  xlarge:
    cpus: 64
    memory: 480
  large:
    cpus: 28
    memory: 246
  medium:
    cpus: 14
    memory: 121
  small:
    cpus: 7
    memory: 14
  tiny:
    cpus: 1
    memory: 1

```

Commandline:
`nextflow run main.nf -work-dir workdir -profile standard -entry wPipeline -params-file ../fullPipeline.yml -resume`
